In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [4]:
credits = pd.read_csv(r"tmdb_5000_credits.csv")
movies = pd.read_csv(r"tmdb_5000_movies.csv")

In [5]:
credits.head(1)

movie_id   title                                               cast  \
0     19995  Avatar  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [6]:
credits.shape

(4803, 4)

In [7]:
credits.head(1)['crew'].values

array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cam

In [8]:
movies.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title  vote_average  vote_count  
0  Enter the World of Pandora.  Avatar           7.2       11800

In [9]:
movies.shape

(4803, 20)

Now we are merging both datasets. We can merge them using either the Movie ID or the Movie Title, as both tables contain these two common columns.

In [10]:
# Reload fresh data
credits = pd.read_csv(r"tmdb_5000_credits.csv")
movies = pd.read_csv(r"tmdb_5000_movies.csv")

print("Credits columns:", credits.columns.tolist())
print("Movies columns:", movies.columns.tolist())

# Check if 'title' exists in both
print("\nMovies has 'title':", 'title' in movies.columns)
print("Credits has 'title':", 'title' in credits.columns)

# Merge on title
movies = movies.merge(credits, on='title')
print("\nMerged shape:", movies.shape)
print("Merged columns:", movies.columns.tolist())

Credits columns: ['movie_id', 'title', 'cast', 'crew']
Movies columns: ['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count']

Movies has 'title': True
Credits has 'title': True

Merged shape: (4809, 23)
Merged columns: ['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count', 'movie_id', 'cast', 'crew']


In [11]:
movies.merge(credits, on='title').shape

(4821, 26)

In [12]:
movies.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  ... runtime  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title vote_average vote_count movie_id  \
0  Enter the World of Pandora.  Avatar          7.2      11800    19995   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  

[1 rows x 23 columns]

**Here, we remove the columns that are not required for analysis. The dataset has 23 columns, but since we are building a content-based recommender system, we only keep the columns that help us create tags for each movie**

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4809 non-null   int64  
 1   genres                4809 non-null   object 
 2   homepage              1713 non-null   object 
 3   id                    4809 non-null   int64  
 4   keywords              4809 non-null   object 
 5   original_language     4809 non-null   object 
 6   original_title        4809 non-null   object 
 7   overview              4806 non-null   object 
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object 
 10  production_countries  4809 non-null   object 
 11  release_date          4808 non-null   object 
 12  revenue               4809 non-null   int64  
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object 
 15  status               

In [14]:
# Keep relevant columns
movies = movies[['movie_id','title', 'overview','genres', 'keywords', 'cast', 'crew']]
print("After column selection:")
print(movies.shape)
print(movies.columns.tolist())

After column selection:
(4809, 7)
['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']


We keep the columns genres, id, keywords, title, overview, cast, and crew because these columns contain textual and descriptive information that helps us create tags for each movie.

In [15]:
movies.head()

# This is the dataframe where we have to work

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [16]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
# Check for null values BEFORE dropping
print("Null values before dropna:")
print(movies.isnull().sum())
print("\nNote: Do NOT drop all NaN rows, only drop if specific columns have NaN")

# Only drop rows where cast or crew is NaN (these are our key columns)
movies = movies.dropna(subset=['cast', 'crew', 'genres', 'keywords'])
print("\nNull values after selective dropna:")
print(movies.isnull().sum())
print("Shape after dropna:", movies.shape)

Null values before dropna:
movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

Note: Do NOT drop all NaN rows, only drop if specific columns have NaN

Null values after selective dropna:
movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64
Shape after dropna: (4809, 7)


In [18]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [19]:
movies.duplicated().sum()

np.int64(0)

In [20]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

Here we do preprocessing. The genres column is in dictionary format, so we convert it into a simple list of words like action, adventure, fantasy, and science fiction. This makes the data easy to use for creating tags

In [21]:
import ast
ast.literal_eval

<function ast.literal_eval(node_or_string)>

In [22]:
## We import ast to convert string data into a Python-readable format like list or dictionary

In [23]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [24]:
# convert([{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}])

In [25]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4809, dtype: object

In [26]:
movies['genres'] = movies['genres'].apply(convert)

In [27]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [28]:
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...                        
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4809, dtype: object

In [29]:
movies['keywords'] = movies['keywords'].apply(convert)

In [30]:
def convert3(obj):
    if isinstance(obj, str):
        try:
            data = ast.literal_eval(obj)
            if isinstance(data, list) and len(data) > 0:
                return [i['name'] for i in data[:3]]
        except (ValueError, SyntaxError):
            pass
    return []

In [31]:
# Now apply convert3
movies['cast'] = movies['cast'].apply(convert3)

print("Cast after conversion:")
print(movies['cast'].head(10))

Cast after conversion:
0     [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1        [Johnny Depp, Orlando Bloom, Keira Knightley]
2         [Daniel Craig, Christoph Waltz, Léa Seydoux]
3         [Christian Bale, Michael Caine, Gary Oldman]
4       [Taylor Kitsch, Lynn Collins, Samantha Morton]
5         [Tobey Maguire, Kirsten Dunst, James Franco]
6            [Zachary Levi, Mandy Moore, Donna Murphy]
7    [Robert Downey Jr., Chris Hemsworth, Mark Ruff...
8        [Daniel Radcliffe, Rupert Grint, Emma Watson]
9               [Ben Affleck, Henry Cavill, Gal Gadot]
Name: cast, dtype: object


In [32]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [33]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...         
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4809, dtype: object

In [34]:
movies['crew'] = movies['crew'].apply(fetch_director) 

In [35]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                               cast                 crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]      [James Cameron]  
1     [Johnny Depp, Orlando Bloom, Keira Knightley]     [Gore Verbinski]  
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]         [Sam Mendes]  
3      [Christian Bale, Michael Caine, Gary Oldman]  [Christopher Nolan]  
4    [Taylor Kitsch, Lynn Collins, Samantha Morton]     [Andrew Stanton]

In [36]:
movies['overview'] = movies['overview'].fillna('').apply(lambda x: x.split())

In [37]:
movies['overview'].isna().sum()

np.int64(0)

In [38]:
x = np.int64(3)

type(x)

numpy.int64

In [39]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                               cast                 crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]      [James Cameron]  
1     [Johnny Depp, Orlando Bloom, Keira Knightley]     [Gore Verbinski]  
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]         [Sam Mendes]  
3      [Christian Bale, Michael Caine, Gary Oldman]  [Christopher Nolan]  
4    [Taylor Kitsch, Lynn Collins, Samantha Morton]     [Andrew Stanton]

Why We Convert Names into Single Entities

When creating tags, each name must be treated as one unique entity.

For example:

Sam Worthington


If the space is kept, the model splits it into:

Sam | Worthington


The word “Sam” is common (Sam Worthington, Sam Mendes, Sam Neill), which can confuse the model and lead to incorrect recommendations.

Solution

We remove spaces and convert names into single tokens:

SamWorthington, SamMendes, SamNeill

Benefit

Avoids confusion between similar names

Preserves unique identities

Improves recommendation accuracy

In [40]:
movies['genres'].apply(lambda x:[i.replace("","") for i in x])

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4809, dtype: object

In [41]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace("","") for i in x])

In [42]:
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace("","") for i in x])

In [43]:
movies['crew'] = movies['crew'].apply(lambda x:[i.replace("","") for i in x])

In [44]:
movies['cast'] = movies['cast'].apply(lambda x:[i.replace("","") for i in x])

In [45]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [46]:
# Combine tags - overview keeps spaces (join with space), others concatenate without spaces
movies['tags'] = movies.apply(lambda row: ' '.join(row['overview']) + ''.join(row['genres']) + ''.join(row['keywords']) + ''.join(row['cast']) + ''.join(row['crew']), axis=1)

In [47]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                               cast                 crew  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]      [James Cameron]   
1     [Johnny Depp, Orlando Bloom, Keira Knightley]     [Gore Verbinski]   
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]         [Sam Mendes]   
3      [Christian Bale, Michael Caine, Gary Oldman]  [Christopher Nolan]   
4    [Taylor Kitsch, Lynn Collins, Samantha Morton]     [Andrew Stanton]   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [48]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
#new.head()

In [49]:
new['tags'] = new['tags'].apply(lambda x: "".join(x))
new.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [50]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                               cast                 crew  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]      [James Cameron]   
1     [Johnny Depp, Orlando Bloom, Keira Knightley]     [Gore Verbinski]   
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]         [Sam Mendes]   
3      [Christian Bale, Michael Caine, Gary Oldman]  [Christopher Nolan]   
4    [Taylor Kitsch, Lynn Collins, Samantha Morton]     [Andrew Stanton]   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [51]:
new_df = movies[['movie_id', 'title', 'tags']]

In [52]:
new_df

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4804      9367                               El Mariachi   
4805     72766                                 Newlyweds   
4806    231617                 Signed, Sealed, Delivered   
4807    126186                          Shanghai Calling   
4808     25975                         My Date with Drew   

                                                   tags  
0     In the 22nd century, a paraplegic Marine is di...  
1     Captain Barbossa, long believed to be dead, ha...  
2     A cryptic message from Bond’s past sends him o...  
3     Following the death of District Attorney Harve...  
4     John Carter is a war-weary, former military ca...  
...                                                 ...  
4804  El Mariachi just wants to play his guitar and ...  
4805  A newlywed couple's honeymoon is upended by th...  
4806  "Signed, Sealed, Delivered" introduces a dedic...  
4807  When ambitious New York attorney Sam is sent t...  
4808  Ever since the second grade when he first saw ...  

[4809 rows x 3 columns]

In [53]:
new_df['tags'].apply(lambda x: "".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...                        
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4809, dtype: object

In [54]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [55]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.ActionAdventureFantasyScience Fictionculture clashfuturespace warspace colonysocietyspace travelfuturisticromancespacealientribealien planetcgimarinesoldierbattlelove affairanti warpower relationsmind and soul3dSam WorthingtonZoe SaldanaSigourney WeaverJames Cameron'

In [56]:
new_df['tags'] = new_df['tags'].apply(lambda x: "".join(x))

C:\Users\shali\AppData\Local\Temp\ipykernel_19264\1819583025.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: "".join(x))


In [57]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [58]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.ActionAdventureFantasyScience Fictionculture clashfuturespace warspace colonysocietyspace travelfuturisticromancespacealientribealien planetcgimarinesoldierbattlelove affairanti warpower relationsmind and soul3dSam WorthingtonZoe SaldanaSigourney WeaverJames Cameron'

In [59]:
new_df['tags'][1]

"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.AdventureFantasyActionoceandrug abuseexotic islandeast india trading companylove of one's lifetraitorshipwreckstrong womanshipalliancecalypsoafterlifefighterpirateswashbuckleraftercreditsstingerJohnny DeppOrlando BloomKeira KnightleyGore Verbinski"

find the similarity between movie1 means tags[0] and movie2 and tags[1]

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [61]:
cv.fit_transform(new_df['tags']).toarray().shape

(4809, 5000)

In [62]:
vectors = cv.fit_transform(new_df['tags']).toarray()
# cv is the object 

In [63]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4809, 5000))

In [64]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

## The movie tags (text data) have been successfully converted into numerical vectors using CountVectorizer.

Total movies: 4809
Maximum features: 5000
Vector shape: (4809, 5000)
Each movie is now represented as a 5000-dimensional vector, where each position corresponds to a word from the vocabulary

Vectorization of Movie Tags

To find the similarity between movies, we need to convert textual tags into numerical form.
This process is called vectorization.

We use CountVectorizer to transform each movie’s tags into a fixed-length numerical vector, where:

Each column represents a unique word (feature)

Each row represents a movie

The value indicates the frequency of a word in that movie’s tags

Why Vectorization Is Required

Machine learning models cannot work directly with text data.
By converting tags into vectors, we make it possible to mathematically compare movies.

For example:

tags[0] → vector of Movie 1

tags[1] → vector of Movie 2

The similarity between two movies is then calculated using these vectors.

Result of Vectorization

Total movies → 4809

Maximum features → 5000

Vector shape → (4809, 5000)

Each movie is now represented as a numerical vector, enabling similarity computation.

✅ Outcome

Text data → Numerical vectors → Similarity calculation → Movie recommendations 

In [65]:
cv.get_feature_names_out()


array(['000', '007', '10', ..., 'zoo', 'zucker', 'zwick'],
      shape=(5000,), dtype=object)

In [66]:
CountVectorizer(max_features=5000)


CountVectorizer(max_features=5000)

In [67]:
len(cv.get_feature_names_out())


5000

## We use the NLTK library to reduce different forms of a word (like loved, loving, love) into a single base word (love), so the model treats them as the same meaning ##

NLTK is used for stemming or lemmatization, which converts words such as loved, loving, and love into a common base form (love), reducing redundancy and improving similarity calculation.

Without NLTK:
love ≠ loved ≠ loving

With NLTK:
love = loved = loving

Result: better understanding + better recommendations

In [68]:
! pip install nltk

Defaulting to user installation because normal site-packages is not writeable


In [69]:
import nltk

In [70]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

We create ps as an instance of PorterStemmer to use its stem() method, which converts different forms of a word into a common root word, improving text similarity.

PorterStemmer is a class (a blueprint)
ps is an object (instance) of that class
ps now has the ability to reduce words to their root form

ps.stem('loving')
Output: 'love'

ps.stem():
Takes one word
Removes suffixes like -ing, -ed, -s
Returns the base/root word

ps.stem('loving') → 'love'
ps.stem('loved')  → 'love'
ps.stem('loves')  → 'love'

So the model understands:  loving = loved = love

Without stemming → model treats them as different words
With stemming → model treats them as same meaning
This reduces noise and improves similarity accuracy

In [71]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)


In [72]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...                        
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4809, dtype: object

In [73]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\shali\AppData\Local\Temp\ipykernel_19264\3213734980.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)


In [74]:
ps.stem('loving')

'love'

In [75]:
ps.stem('loved')

'love'

In [76]:
ps.stem('dancing')

'danc'

In [77]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.ActionAdventureFantasyScience Fictionculture clashfuturespace warspace colonysocietyspace travelfuturisticromancespacealientribealien planetcgimarinesoldierbattlelove affairanti warpower relationsmind and soul3dSam WorthingtonZoe SaldanaSigourney WeaverJames Cameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization.actionadventurefantasysci fictioncultur clashfuturespac warspac colonysocietyspac travelfuturisticromancespacealientribealien planetcgimarinesoldierbattlelov affairanti warpow relationsmind and soul3dsam worthingtonzo saldanasigourney weaverjam cameron'

marine → marin

unique → uniq

In [78]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...                        
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4809, dtype: object

In [79]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\shali\AppData\Local\Temp\ipykernel_19264\3213734980.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)


## NLTK stemming has been successfully completed, converting words like *marine* to *marin* and ensuring consistent text representation across all 4,809 movie tags.


In [80]:
from sklearn.metrics.pairwise import cosine_similarity

Cosine Similarity is used in this movie recommendation system to measure the similarity between movies based on their feature vectors. Each movie is represented using binary values, where 1 indicates the presence of a feature and 0 indicates its absence. Cosine Similarity computes the angle between these vectors, producing a similarity score between 0 and 1. A higher score means the movies share more common features and are therefore more similar, making it suitable for recommending related movies.

In [81]:
cosine_similarity(vectors).shape

(4809, 4809)

In [82]:
similarity = cosine_similarity(vectors)

In [83]:
similarity[0]

array([1., 0., 0., ..., 0., 0., 0.], shape=(4809,))

This is the similarity scores of Movie 0 with ALL movies

similarity[0][0] = 1
Movie 0 compared with itself → 100% similar

Other values (0, 0.84, etc.)
➜ How similar Movie 0 is to other movies

So:

similarity[0] = “How similar movie index 0 is to every movie in the dataset”

In [84]:
similarity[1]

array([0.        , 1.        , 0.        , ..., 0.04303315, 0.        ,
       0.        ], shape=(4809,))

This is the similarity scores of Movie 1 with ALL movies

similarity[1][1] = 1
Movie 1 compared with itself

Other values show similarity with other movies

So:

similarity[1] = “How similar movie index 1 is to every movie”

In [85]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]

    for i in movie_list:
        print(i[0])

In [86]:
sorted(similarity[0],reverse = True)

[np.float64(0.9999999999999998),
 np.float64(0.2419433515636535),
 np.float64(0.23094010767585027),
 np.float64(0.16129556770910236),
 np.float64(0.14322297480788657),
 np.float64(0.12524485821702988),
 np.float64(0.12433397443204182),
 np.float64(0.12171612389003691),
 np.float64(0.12171612389003691),
 np.float64(0.11547005383792514),
 np.float64(0.11547005383792514),
 np.float64(0.11547005383792514),
 np.float64(0.11547005383792514),
 np.float64(0.11547005383792514),
 np.float64(0.1126872339638022),
 np.float64(0.11180339887498948),
 np.float64(0.11009637651263604),
 np.float64(0.11009637651263604),
 np.float64(0.10954451150103321),
 np.float64(0.10846522890932808),
 np.float64(0.10767638041163309),
 np.float64(0.10741723110591492),
 np.float64(0.10127393670836665),
 np.float64(0.09938079899999065),
 np.float64(0.09938079899999065),
 np.float64(0.09938079899999065),
 np.float64(0.09938079899999065),
 np.float64(0.0975900072948533),
 np.float64(0.0975900072948533),
 np.float64(0.09759

In [87]:
list(enumerate(similarity))


[(0, array([1., 0., 0., ..., 0., 0., 0.], shape=(4809,))),
 (1,
  array([0.        , 1.        , 0.        , ..., 0.04303315, 0.        ,
         0.        ], shape=(4809,))),
 (2,
  array([0.        , 0.        , 1.        , ..., 0.03333333, 0.        ,
         0.        ], shape=(4809,))),
 (3,
  array([0.03651484, 0.        , 0.        , ..., 0.04714045, 0.07071068,
         0.07071068], shape=(4809,))),
 (4,
  array([0.        , 0.04714045, 0.        , ..., 0.03042903, 0.        ,
         0.        ], shape=(4809,))),
 (5,
  array([0.04637389, 0.        , 0.        , ..., 0.02993422, 0.02993422,
         0.02993422], shape=(4809,))),
 (6,
  array([0.        , 0.        , 0.        , ..., 0.        , 0.02289343,
         0.02289343], shape=(4809,))),
 (7,
  array([0.04494666, 0.04494666, 0.03481553, ..., 0.        , 0.        ,
         0.        ], shape=(4809,))),
 (8,
  array([0.        , 0.        , 0.04170288, ..., 0.0695048 , 0.0695048 ,
         0.0695048 ], shape=(4809,))

In [88]:
list(enumerate(similarity[0]))


[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.03651483716701107)),
 (4, np.float64(0.0)),
 (5, np.float64(0.046373889576016826)),
 (6, np.float64(0.0)),
 (7, np.float64(0.04494665749754947)),
 (8, np.float64(0.0)),
 (9, np.float64(0.0)),
 (10, np.float64(0.0)),
 (11, np.float64(0.046373889576016826)),
 (12, np.float64(0.0)),
 (13, np.float64(0.0)),
 (14, np.float64(0.051639777949432225)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (17, np.float64(0.0)),
 (18, np.float64(0.0)),
 (19, np.float64(0.0)),
 (20, np.float64(0.0)),
 (21, np.float64(0.0)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.0)),
 (25, np.float64(0.031544014893825585)),
 (26, np.float64(0.053838190205816545)),
 (27, np.float64(0.07093269021319086)),
 (28, np.float64(0.0)),
 (29, np.float64(0.039374961547907886)),
 (30, np.float64(0.0)),
 (31, np.float64(0.06085806194501846)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.floa

## Understanding `similarity[0]` in Movie Recommendation System

When we write:

```python
list(enumerate(similarity[0]))
it means:

We are checking how similar the 0th movie is with every other movie in the dataset.

How to read the output
Each element looks like this:

(movie_index, similarity_score)
Example:

(3, 0.0365)
This means:

Movie 0 is compared with movie 3

Their cosine similarity score is 0.

Important cases

(0, 0.9999)

Movie 0 compared with itself

Similarity is ≈ 1 (100% similar)

(1, 0.0)

Movie 0 vs Movie 1

Similarity is 0 → no common features/tags

Small values like 0.04, 0.05

Movies share some common words or tags

Slight similarity exists

In [89]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])


[(0, np.float64(0.9999999999999998)),
 (3607, np.float64(0.2419433515636535)),
 (151, np.float64(0.23094010767585027)),
 (529, np.float64(0.16129556770910236)),
 (2132, np.float64(0.14322297480788657)),
 (942, np.float64(0.12524485821702988)),
 (1214, np.float64(0.12433397443204182)),
 (568, np.float64(0.12171612389003691)),
 (1612, np.float64(0.12171612389003691)),
 (972, np.float64(0.11547005383792514)),
 (973, np.float64(0.11547005383792514)),
 (1275, np.float64(0.11547005383792514)),
 (1786, np.float64(0.11547005383792514)),
 (2618, np.float64(0.11547005383792514)),
 (3487, np.float64(0.1126872339638022)),
 (2970, np.float64(0.11180339887498948)),
 (3339, np.float64(0.11009637651263604)),
 (3621, np.float64(0.11009637651263604)),
 (1530, np.float64(0.10954451150103321)),
 (150, np.float64(0.10846522890932808)),
 (2616, np.float64(0.10767638041163309)),
 (1961, np.float64(0.10741723110591492)),
 (1159, np.float64(0.10127393670836665)),
 (311, np.float64(0.09938079899999065)),
 (986,

Meaning:

First element → same movie (always 1.0)

Next elements → most similar movies to movie 0

Last elements → least similar movies

In one simple line (remember this!)

This code returns all movies sorted by how similar they are to the 0th movie, from most similar to least similar.

## 1. (0, 0.9999999999999998)

Movie 0 compared with itself

Similarity ≈ 1

Always comes first
Ignore this while recommending

## 2. (3607, 0.2419)

Movie 3607 is the most similar movie to movie 0

Similarity ≈ 0.24
This is your best recommendation

## 3. (151, 0.2309)

Second most similar movie to movie 0

Slightly less similar than 3607

## 4. (529, 0.1613)

Third strongest match

In [90]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]
# That line is supposed to give only 5 recommended movies.

[(3607, np.float64(0.2419433515636535)),
 (151, np.float64(0.23094010767585027)),
 (529, np.float64(0.16129556770910236)),
 (2132, np.float64(0.14322297480788657)),
 (942, np.float64(0.12524485821702988))]

In [91]:
new_df['title'] == 'Avatar'

0        True
1       False
2       False
3       False
4       False
        ...  
4804    False
4805    False
4806    False
4807    False
4808    False
Name: title, Length: 4809, dtype: bool

In [92]:
new_df[new_df['title'] == 'Avatar']

movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [93]:
new_df[new_df['title'] == 'Avatar'].index[0]

np.int64(0)

In [94]:
new_df[new_df['title'] == 'Batman Begins'].index[0]

np.int64(119)

In [95]:
recommend('Batman Begins')

65
962
299
3
1361


In [96]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [97]:
recommend('Avatar')

Apollo 18
Beowulf
Tears of the Sun
The American
The Book of Life


In [98]:
new_df.iloc[1216]

movie_id                                                10641
title                                      Autumn in New York
tags        autumn in new york follow the sexual exploit o...
Name: 1216, dtype: object

The returned row contains the following information:

movie_id
Unique identifier of the movie

10641


title
Name of the movie

Autumn in New York


tags
Combined textual features (such as overview, genres, keywords, etc.)
These tags are used to calculate similarity between movies in the
recommendation system.

Why this is important in a recommender system

Each row represents one movie

The tags column is converted into vectors

Cosine similarity is calculated using these vectors

Similar movies are recommended based on these similarity scores

In [99]:
new_df.iloc[1216].title

'Autumn in New York'

In [100]:
recommend('Batman Begins')

The Dark Knight
Raising Helen
Batman Forever
The Dark Knight Rises
Batman


The recommender system has learned relationships between movies based on their textual features and recommends movies with similar content to the selected movie.

Interview / Viva-ready explanation

## Now converting this entire thing into a webside

In [101]:
import pickle

We import pickle to save a trained model and load it later.

Real-life ML problem (why it’s needed)

Training a model:

takes time 

uses CPU/GPU 

you don’t want to train it again every time

So we save the trained model once → and reuse it.

What pickle does

pickle converts a Python object (like an ML model) into a file and back.

In ML:

Save model → after training

Load model → when making predictions (website/app)

In [103]:
pickle.dump(new_df, open('movies.plk', 'wb'))
# Model is saved in a file called model.pkl